#ifndef HDR_USER_BLE
#define HDR_USER_BLE


//#define EN_220_ATT_MTU 0x01U
#define EN_512_ATT_MTU 0x01U

#if (EN_512_ATT_MTU)

#define	USER_CTRL_CODE_ATT_DATA				0x10
#define USER_CUSTOM_ATT_MTU_SIZE			512U
#define USER_ALWD_NUM_LINK						0x01U
#else
#define USER_CUSTOM_ATT_MTU_SIZE			220U
#define USER_ALWD_NUM_LINK						0x08U
#endif /*EN_512_ATT_MTU*/

#define EXTRA_BYTES_2AVOID_BUFF_OVFLOW	30U

#define USER_HCI_PCKT_SIZE						USER_CUSTOM_ATT_MTU_SIZE+EXTRA_BYTES_2AVOID_BUFF_OVFLOW				

#define CUSTOM_CMD_BUFF_SIZE					USER_CUSTOM_ATT_MTU_SIZE+	EXTRA_BYTES_2AVOID_BUFF_OVFLOW

#define CUSTOM_EVT_BUFFER_SIZE				1024U+USER_CUSTOM_ATT_MTU_SIZE

#define CUSTOM_MAX_PAYLOAD_SIZE				USER_CUSTOM_ATT_MTU_SIZE+	EXTRA_BYTES_2AVOID_BUFF_OVFLOW


#endif /*HDR_USER_BLE*/
